import Head from "next/head";

//Layout imports
import Footer from "./footer";
import Navbar from "./navbar";

export default function Layout({ children, title, pageTitle }) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="img/favicon.ico" />
      </Head>

      <Navbar />

      <main className="container main-content">
        <div className="text-center">
          <h1>{pageTitle}</h1>
          <hr className="my-3" style={{ width: "80%", margin: "auto" }} />
        </div>
        {children}
      </main>

      <Footer />
    </>
  );
}

Layout.defaultProps = {
  title: "NextUsers",
  pageTitle: "Page",
};
